# Setup {#setup}

This page will take you through all steps necessary to fully setup your computer. There are several things we need to do:

 1. First, in section \@ref(setup-install) we will install both R and Rstudio.
 2. Next, in section \@ref(setup-configure) we will configure Rstudio and install some necessary R packages.
 3. Finally, in section \@ref(setup-files) we will setup an organization system for your files.


## R/Rstudio setup {#setup-install}

We will be using both R and Rstudio throughout the course.

 - [R](https://www.r-project.org/) is a free and open-source statistical computing software.
 - [Rstudio](https://posit.co/products/open-source/rstudio/) is an IDE (integrated development environment) that makes developing in R much easier.
   - If you prefer, you can also use a different IDE like [Visual Studio](https://code.visualstudio.com/docs/languages/r) or [Jupyter](https://docs.anaconda.com/free/navigator/tutorials/r-lang/).

::: {.rmdnote}
Note: R and Rstudio are two different programs that both need to be installed!
:::

The instructions below are separated by operating system, depending on if you have a [Windows](#setup-win) or [Mac](#setup-mac) machine.

 - If you have a Linux system, follow one of the linked instructions [here](https://cloud.r-project.org/bin/linux/).
 - If you have a Chromebook, try [these steps](https://levente.littvay.hu/chromebook/).

### Windows instructions {#setup-win}

`r lorem::ipsum(3)`

### Mac instructions {#setup-mac}

`r lorem::ipsum(3)`

## R configuration/packages {#setup-configure}

`r lorem::ipsum(3)`

## File organization {#setup-files}

`r lorem::ipsum(3)`
