

# Cheat sheets

Below is a consolidation of all "cheat sheets" mentioned in the notes, as well as a few extra that are not mentioned. This page is intended for you to use as a quick reference for basically the entire course without needing to dig through the notes. They're *loosely* organized by order of appearance.


## Rstudio IDE

The [Rstudio cheat sheet](https://rstudio.github.io/cheatsheets/rstudio-ide.pdf) has a VERY detailed description of what every button in Rstudio does, as well as some additional tips like common keyboard shortcuts and workflow suggestions.


## Base R

 - Matt Baggott's [R Reference Card v2.0](https://cran.r-project.org/doc/contrib/Baggott-refcard-v2.pdf) is a nice complete one-stop-shop for all of R's built-in functions.
 - IQSS's [Base R Cheat Sheet](https://iqss.github.io/dss-workshops/R/Rintro/base-r-cheat-sheet.pdf) and Alexey Shipunov's [One Page R Reference Card](https://herba.msu.ru/shipunov/school/biol_240/en/supp/refcard/rrefc_en.pdf) are both slightly shorter and more curated, but offer a nice, tighter set of the most critical R commands, along with useful examples of their syntax.
 - For a slightly longer but more complete reference manual on R, especially with more details of how R works and different object types and data structures, Emmanuel Paradis's [R for Beginners](https://cran.r-project.org/doc/contrib/Paradis-rdebuts_en.pdf) may be helpful.


## R Markdown

 - The [R Markdown cheat sheet](https://rstudio.github.io/cheatsheets/rmarkdown.pdf) has a convenient summary of everything you need to know and more to effectively use R Markdown, including basic markdown syntax, common chunk/YAML options, additional styling settings, and more.
 - There's also a slightly longer [R Markdown reference guide](https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf) with a longer list of chunk and YAML options.
 - There's also a separate [Markdown](https://markdownguide.offshoot.io/cheat-sheet) cheat sheet; note the basic syntax is completely supported, but some of the extended syntax is not supported. Feel free to experiment more on your own.


## $\LaTeX$

If you wish to read more on $\LaTeX$, start with Rong Zhuang's [MathJax cheat sheet](https://jojozhuang.github.io/tutorial/mathjax-cheat-sheet-for-mathematical-notation) or David Richeson's [quick guide](https://users.dickinson.edu/~richesod/latex/latexcheatsheet.pdf) which both have lots of great beginner-friendly examples. For a slightly more complete list of symbols, Eric Torrence's [cheat sheet](https://pages.uoregon.edu/torrence/391/labs/LaTeX-cheat-sheet.pdf) may also be useful. 


## readr

The [readr cheat sheet](https://rstudio.github.io/cheatsheets/data-import.pdf) has a good overview of all `read_*` functions as well as example code and some common arguments.


## lubridate

The first page of the [lubridate cheat sheet](https://rstudio.github.io/cheatsheets/lubridate.pdf) is useful for quickly checking if you're using the right date-related operation.


## ggplot2

The [ggplot2 cheat sheet](https://rstudio.github.io/cheatsheets/data-visualization.pdf) has a great summary of every plot type on the first page, organized by the type and number of variables it's designed to visualize. On the second page, there's a nice list of additional plot features, such as faceting (i.e. subplot) options, setting scales, adjusting positions of plot elements, changing themes, editing labels/legends, etc.


## dplyr

The [dplyr cheat sheet](https://rstudio.github.io/cheatsheets/data-transformation.pdf) has a basic rundown of all common data frame transformation operations, grouped by type, along with brief but helpful examples and diagrams. It includes everything from subsetting rows and columns, adding/editing columns, summarizing data frames, grouping operations, joining/binding multiple data frames, etc.



<!--
https://rstudio.github.io/cheatsheets/
-->
